name: Prometheus SDET Challenge CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-api:
    name: test (api, ApiTests/ApiTests.csproj)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET (7.0 + 8.0)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore ApiTests/ApiTests.csproj

      - name: Build API project
        run: dotnet build ApiTests/ApiTests.csproj --configuration Release --no-restore

      - name: Run API tests
        run: dotnet test ApiTests/ApiTests.csproj --logger "trx;LogFileName=api-tests.trx"
        continue-on-error: false

      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: "**/api-tests.trx"


  test-ui:
    name: test (ui, UiTests/UiTests.csproj)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET (7.0 + 8.0)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x

      - name: Restore dependencies
        run: dotnet restore UiTests/UiTests.csproj

      - name: Build UI project
        run: dotnet build UiTests/UiTests.csproj --configuration Release --no-restore

      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright..."
          pwsh -command "npx playwright install --with-deps"

      - name: Run UI tests
        run: dotnet test UiTests/UiTests.csproj --logger "trx;LogFileName=ui-tests.trx"
        continue-on-error: false

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: "**/ui-tests.trx"
