name: Prometheus SDET Challenge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  api-tests:
    name: test (api, ApiTests/ApiTests.csproj)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ApiTests/ApiTests.csproj

      - name: Build API project
        run: dotnet build ApiTests/ApiTests.csproj --configuration Release --no-restore

      - name: Run API tests
        run: dotnet test ApiTests/ApiTests.csproj --logger trx --results-directory TestResults

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults/


  ui-tests:
    name: test (ui, UiTests/UiTests.csproj)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore UiTests/UiTests.csproj

      - name: Build UI project
        run: dotnet build UiTests/UiTests.csproj --configuration Release --no-restore

      # ðŸ‘‰ IMPORTANT: Install browsers AFTER build
      - name: Install Playwright browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Run UI tests
        env:
          HEADED: true
        run: dotnet test UiTests/UiTests.csproj --logger trx --results-directory TestResults

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-res
